import {
  Activity,
  Bell,
  Bookmark,
  BatteryFull,
  Camera,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Copy,
  CreditCard,
  Dumbbell,
  Flame,
  FolderPlus,
  Flower2,
  Gift,
  GraduationCap,
  Heart,
  House,
  Lock,
  Mail,
  MapPinned,
  MessageSquare,
  MessagesSquare,
  Signal,
  Smartphone,
  Swords,
  UserRound,
  Wifi,
  Zap,
} from 'lucide-react-native';

/** Kebab-case Lucide names (as used by the BMOG design kit) mapped to their lucide-react-native components. */
export const BrandIcons = {
  activity: Activity,
  bell: Bell,
  bookmark: Bookmark,
  'battery-full': BatteryFull,
  camera: Camera,
  'calendar-days': CalendarDays,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  copy: Copy,
  'credit-card': CreditCard,
  dumbbell: Dumbbell,
  flame: Flame,
  'folder-plus': FolderPlus,
  'flower-2': Flower2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  heart: Heart,
  house: House,
  lock: Lock,
  mail: Mail,
  'map-pinned': MapPinned,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  signal: Signal,
  smartphone: Smartphone,
  swords: Swords,
  'user-round': UserRound,
  wifi: Wifi,
  zap: Zap,
} as const;

export type BrandIconName = keyof typeof BrandIcons;
