import {
  Activity,
  AlertTriangle,
  ArrowUp,
  Bell,
  Bookmark,
  BatteryFull,
  Calendar,
  CalendarCheck,
  Camera,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  CreditCard,
  Dumbbell,
  ExternalLink,
  Flame,
  FolderOutput,
  FolderPlus,
  Flower2,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  House,
  Info,
  Link2,
  Lock,
  Mail,
  MapPin,
  MapPinned,
  MessageSquare,
  MessagesSquare,
  Minus,
  Pencil,
  Phone,
  Plus,
  ScanLine,
  Search,
  Share2,
  ShieldAlert,
  Signal,
  Smartphone,
  Smile,
  Star,
  Swords,
  Trash2,
  UserPlus,
  UserRound,
  Users,
  Wallet,
  Wifi,
  X,
  Zap,
} from 'lucide-react-native';

/** Kebab-case Lucide names (as used by the BMOG design kit) mapped to their lucide-react-native components. */
export const BrandIcons = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-up': ArrowUp,
  bell: Bell,
  bookmark: Bookmark,
  'battery-full': BatteryFull,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  camera: Camera,
  'calendar-days': CalendarDays,
  check: Check,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  clock: Clock,
  copy: Copy,
  'credit-card': CreditCard,
  dumbbell: Dumbbell,
  'external-link': ExternalLink,
  flame: Flame,
  'folder-output': FolderOutput,
  'folder-plus': FolderPlus,
  'flower-2': Flower2,
  gift: Gift,
  globe: Globe,
  'graduation-cap': GraduationCap,
  heart: Heart,
  house: House,
  info: Info,
  'link-2': Link2,
  lock: Lock,
  mail: Mail,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  minus: Minus,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  'scan-line': ScanLine,
  search: Search,
  'share-2': Share2,
  'shield-alert': ShieldAlert,
  signal: Signal,
  smartphone: Smartphone,
  smile: Smile,
  star: Star,
  swords: Swords,
  'trash-2': Trash2,
  'user-plus': UserPlus,
  'user-round': UserRound,
  users: Users,
  wallet: Wallet,
  wifi: Wifi,
  x: X,
  zap: Zap,
} as const;

export type BrandIconName = keyof typeof BrandIcons;
